export const SAVE_PRODUCTS = 'SAVE_PRODUCTS';
export const FETCH_PRODUCTS_ATTEMPT = 'FETCH_PRODUCTS_ATTEMPT';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';